### ISSUE TITLE
问个弱弱的问题?

### ISSUE THREAD

**Issue by ShangJunFengg** [sanshengshui/netty-learning-example#4]
大佬,java做物联网怎么入门啊,我目前一直在做javaweb开发,想转型下.
是不是要自己买硬件连一下啊?求给个方向啊,光写netty没实践感觉用不上啊

**Comment by sanshengshui** [comment]
不需要啊！你可以用mqtt.js和paho等工具进行软件模拟设备，一样可以做到。
