### ISSUE TITLE
请问现在支持SSL/TLS吗？

### ISSUE THREAD

**Issue by wangzengjing** [sanshengshui/netty-learning-example#6]
前辈，现在netty+mqtt 服务端支持ssl/tls 认证吗？感觉安全性方面需要

**Comment by sanshengshui** [comment]
支持的，相关知识你查阅一下，很好实现的

**Comment by wangzengjing** [comment]
好的，这几天正在看，还有我想请问一下MessageIdServiceImpl中方法是不是还没有实现，想请教一下实现的思路，谢谢大佬

**Comment by sanshengshui** [comment]
这个最近比较忙，我改天把相关的修改一下，应该没实现吧

**Comment by wangzengjing** [comment]
好的，谢谢

**Comment by wangzengjing** [comment]
大佬，我这边刚刚试试设置遗嘱消息质量为1或2的时候，就会爆出MessageId：0的错误，设置消息质量为0的时候就没这个问题，刚刚入门不是很了解错误，猜是MessageIdServiceImpl没实现，期待大佬修改代码的时候
