### ISSUE TITLE
请问netty+mqtt服务端集群方案如何实现

### ISSUE THREAD

**Issue by heaven9277** [sanshengshui/netty-learning-example#7]
作者您好，我现在正在使用你的netty+mqtt实现服务端做练习，想请教一下如何实现集群，有没有相应的例子？

**Comment by sanshengshui** [comment]
关于服务端集群的化，需要借助注册中心来实现．例如我们可以弄一个zookeeper,用于每一个mqtt服务端的注册于发现．当然还有很多内在的问题需要考虑！请自行思考一下

**Comment by heaven9277** [comment]
多谢，一直都在找相关的资料查看，但新手入门对这些接触不是很多


------------------ 原始邮件 ------------------
发件人: "jamesmsw"<notifications@github.com>;
发送时间: 2019年6月27日(星期四) 晚上6:43
收件人: "sanshengshui/netty-learning-example"<netty-learning-example@noreply.github.com>;
抄送: "疯"<2323421172@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sanshengshui/netty-learning-example] 请问netty+mqtt服务端集群方案如何实现 (#7)




关于服务端集群的化，需要借助注册中心来实现．例如我们可以弄一个zookeeper,用于每一个mqtt服务端的注册于发现．当然还有很多内在的问题需要考虑！请自行思考一下
