### ISSUE TITLE
mqtt工程的MqttTransportHandler

### ISSUE THREAD

**Issue by 1193829006** [sanshengshui/netty-learning-example#8]
不好意思，刚刚开始看这个mqtt的工程，MqttTransportHandler 为什么要加上共享这个handler注解？ 这样做线程安全怎么保证吗？

**Comment by 1193829006** [comment]
是因为这个handler是无状态的吗？

**Comment by sanshengshui** [comment]
是这样的，那个类只用作消息类型的判断和处理异常情况．没有拥有状态．:smiling_imp:
你说的对，只有确保ChannelHandler是线程安全的，才能使用@Sharable. :thumbsup:
只有怎么判断和保证类的线程安全，需要我们开发人员自己的知识积累和判断了 :clap:

**Comment by 1193829006** [comment]
感谢感谢

**Comment by 1193829006** [comment]
大佬 又有问题了 订阅跟发送qos都为2 订阅端接收不到消息是为什么

**Comment by 1193829006** [comment]
如果订阅者的qos<1 就能收到消息，这是为什么

**Comment by sanshengshui** [comment]
这个问题，我找了一晚上，没找出来！:crystal_ball: 等我振作精神，再找找 :dart:

**Comment by 1193829006** [comment]
哈哈 我也找了两天了，也没找到

**Comment by 1193829006** [comment]
我大概知道什么原因了，现在太晚了，对照一下mqtt的qos2的流程，再对比一下mqtt的级别码 能发现问题

**Comment by sanshengshui** [comment]
那你测试，测试一下．提交一个pull request吧！

**Comment by 1193829006** [comment]
稍等 在上班  估计要明天

**Comment by sanshengshui** [comment]
:beers:

**Comment by 1193829006** [comment]
大佬 我错了  应该是id重复的问题 不好意思最近有点忙 
Publish 类下的 sendPublishMessage 方法  qos2 那个判断下面 new MqttPublishVariableHeader(topic, ***)这里的消息 重复了 我是抓了包之后发现 这条消息因为跟发送端的一直 好像被去重了，把这个***改成其他的数字 就可以了 不好意思啊 最近有点忙 没怎么有时间看

**Comment by sanshengshui** [comment]
你真是一个机灵而又认真的boy啊！给你一颗心　:heartpulse:　都想给你颁奖了！:sparkles:
