### ISSUE TITLE
helloworld写法有些问题

### ISSUE THREAD

**Issue by scneuzb** [sanshengshui/netty-learning-example#9]
helloworld里的ServerInitializer.java
private static final ServerHandler SERVER_HANDLER = new ServerHandler();
这里用了static final，所以这个server只能连接一次，客户端断开就再也连不上了。

**Comment by sanshengshui** [comment]
这个是没有任何问题的，当客户端向服务端发送“bye”时，服务端会主动断开两者的通信，客户端同理。所以连不上啊，你重启一下客户端的启动类，会重新建立连接的，请仔细了解下！

**Comment by scneuzb** [comment]
你自己试试再说，我也是够闲的。
pipeline.addLast(new ServerHandler());
这样写才不会有问题，否则只能连一次。

**Comment by sanshengshui** [comment]
我只能录个视频，你看下和你自己环境不一样吗？

https://james-1258744956.cos.ap-shanghai.myqcloud.com/issues/netty-helloworld.mp4

**Comment by scneuzb** [comment]
我已经说了这个只能运行一次，你只运行一次客户端或者启动多个客户端就连不上了。我说的不够清楚？
